name: Example Workflow

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    outputs:
      job1Step2Output: ${{ steps.step2.outputs.job1Step2Output }}

    steps:
      - name: Step 1 of Job 1
        run: echo "This is step 1 of job 1"

      - name: Step 2 of Job 1
        id: step2
        run: |
          echo "job1Step2Output1=Hello World Again" >> $GITHUB_OUTPUT
          echo "job1Step2Output=Hello World" >> $GITHUB_OUTPUT

      - name: Step 3 of Job 1
        id: step3
        run: |
          echo "Output from job-1 step-2: ${{ steps.step2.outputs.job1Step2Output }}"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1

    steps:
      - name: Step 1 of Job 2
        run: echo "This is step 1 of job 2"

      - name: Step 2 of Job 2
        run: |
          echo "Output from job-1 step-2: ${{ needs.job-1.outputs.job1Step2Output }}"
